{% set name = "pynguin" %}
{% set version = "0.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynguin-{{ version }}.tar.gz
  sha256: 02f5c947ec30dc302daf9b46e320866f940a1a193fc3df5fa12a4a1e55cfa42e

build:
  number: 0
  noarch: python
  entry_points:
    - pynguin = pynguin.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.10,<3.11
  run:
    - bytecode >=0,<1
    - jellyfish >=0,<1
    - jinja2 >=3.1
    - mutpy-pynguin >=0.7.1,<0.8.0
    - networkx ==2.8.2
    - ordered-set >=4.1,<5.0
    - pydot >=1.4,<2.0
    - pygments >=2.12
    - pytest >=7.1,<8.0
    - python >=3.10,<3.11
    - rich >=12.4
    - simple-parsing >=0.0.20
    - typing_inspect >=0,<1

test:
  commands:
    - pip check
    - export PYNGUIN_DANGER_AWARE=1
    - python -c 'import pynguin'
    - python -c 'import pynguin.analyses'
    - python -c 'import pynguin.assertion'
    - python -c 'import pynguin.assertion.mutation_analysis'
    - python -c 'import pynguin.coverage'
    - python -c 'import pynguin.ga'
    - python -c 'import pynguin.ga.comparators'
    - python -c 'import pynguin.ga.operators'
    - python -c 'import pynguin.ga.operators.crossover'
    - python -c 'import pynguin.ga.operators.ranking'
    - python -c 'import pynguin.ga.operators.selection'
    - python -c 'import pynguin.generation'
    - python -c 'import pynguin.generation.algorithms'
    - python -c 'import pynguin.generation.stoppingconditions'
    - python -c 'import pynguin.instrumentation'
    - python -c 'import pynguin.resources'
    - python -c 'import pynguin.testcase'
    - python -c 'import pynguin.utils'
    - python -c 'import pynguin.utils.generic'
    - python -c 'import pynguin.utils.statistics'
    - pynguin
  requires:
    - pip

about:
  home: https://github.com/se2p/pynguin
  doc_url: https://pynguin.readthedocs.io/en/latest/
  summary: Pynguin is a tool for automated unit test generation for Python
  license: LGPL-3.0-only
  license_file: LICENSE.rst
  description: |
    Unit test automated generation techniques have been proposed and mature
     tools exist for statically typed languages, such as Java. Pynguin is on of
     the first tool that fills this gap and allows the automated generation of
     unit tests for Python programs.

extra:
  recipe-maintainers:
    - thewchan
