{% set name = "pynguin" %}
{% set version = "0.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynguin-{{ version }}.tar.gz
  sha256: 4555ce399a3a48eec6878ffa68efeeb2dbf175048a427448ff7f5b096f45f8d7

build:
  number: 0
  noarch: python
  entry_points:
    - pynguin = pynguin.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - astor >=0.8.1,<0.9.0
    - bytecode >=0,<1
    - jellyfish >=0,<1
    - jinja2 >=3.0
    - networkx >=2,<3.0
    - ordered-set >=4.0.2
    - pydot >=1.4,<2.0
    - pygments >=2.10.0
    - pytest >=6.2,<7.0
    - python >=3.6,<4.0
    - rich >=10.12,<11.0
    - simple-parsing <0.0.17,>=0.0.16
    - typing_inspect >=0,<1

test:
  commands:
    - pip check
    - export PYNGUIN_DANGER_AWARE=1
    - python -c 'import pynguin'
    - pynguin
  requires:
    - pip

about:
  home: https://github.com/se2p/pynguin
  doc_url: https://pynguin.readthedocs.io/en/latest/
  summary: Pynguin is a tool for automated unit test generation for Python
  license: LGPL-3.0-only
  license_file: LICENSE.rst
  description: |
    Unit test automated generation techniques have been proposed and mature
     tools exist for statically typed languages, such as Java. Pynguin is on of
     the first tool that fills this gap and allows the automated generation of
     unit tests for Python programs.

extra:
  recipe-maintainers:
    - thewchan
