{% set name = "pynguin" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynguin-{{ version }}.tar.gz
  sha256: ccee9e6d85f773228883deaf462cdf3ebf5d96a287e6cb11c46d9302bb9fa72f

build:
  number: 0
  noarch: python
  entry_points:
    - pynguin = pynguin.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.6
  run:
    - astor >=0.8.1,<0.9.0
    - bytecode >=0,<1
    - jellyfish >=0,<1
    - jinja2 >=3.0
    - mutpy-pynguin >=0.7.1
    - networkx >=2,<3.0
    - ordered-set >=4.0
    - pydot >=1.4,<2.0
    - pygments >=2.11,<3.0
    - pytest >=6.2,<7.0
    - python >=3.6
    - rich >=11.0,<12.0
    - simple-parsing >=0.0.17,<0.0.18
    - typing_inspect >=0,<1

test:
  commands:
    - pip check
    - export PYNGUIN_DANGER_AWARE=1
    - python -c 'import pynguin'
    - python -c 'import pynguin.analyses'
    - python -c 'import pynguin.analyses.controlflow'
    - python -c 'import pynguin.analyses.module'
    - python -c 'import pynguin.analyses.seeding'
    - python -c 'import pynguin.analyses.seeding.testimport'
    - python -c 'import pynguin.assertion'
    - python -c 'import pynguin.assertion.mutation_analysis'
    - python -c 'import pynguin.coverage'
    - python -c 'import pynguin.ga'
    - python -c 'import pynguin.ga.comparators'
    - python -c 'import pynguin.ga.operators'
    - python -c 'import pynguin.ga.operators.crossover'
    - python -c 'import pynguin.ga.operators.ranking'
    - python -c 'import pynguin.ga.operators.selection'
    - python -c 'import pynguin.generation'
    - python -c 'import pynguin.generation.algorithms'
    - python -c 'import pynguin.generation.export'
    - python -c 'import pynguin.generation.stoppingconditions'
    - python -c 'import pynguin.instrumentation'
    - python -c 'import pynguin.resources'
    - python -c 'import pynguin.setup'
    - python -c 'import pynguin.testcase'
    - python -c 'import pynguin.typeinference'
    - python -c 'import pynguin.utils'
    - python -c 'import pynguin.utils.generic'
    - python -c 'import pynguin.utils.statistics'
    - pynguin
  requires:
    - pip

about:
  home: https://github.com/se2p/pynguin
  doc_url: https://pynguin.readthedocs.io/en/latest/
  summary: Pynguin is a tool for automated unit test generation for Python
  license: LGPL-3.0-only
  license_file: LICENSE.rst
  description: |
    Unit test automated generation techniques have been proposed and mature
     tools exist for statically typed languages, such as Java. Pynguin is on of
     the first tool that fills this gap and allows the automated generation of
     unit tests for Python programs.

extra:
  recipe-maintainers:
    - thewchan
