{% set name = "pynguin" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynguin-{{ version }}.tar.gz
  sha256: 9b76e17d194dc3b3420793fe8944e41d655c66b43a11e81f0e80794bfd09ae03

build:
  number: 0
  noarch: python
  entry_points:
    - pynguin = pynguin.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.10,<3.11
  run:
    - asciitree >=0.3.3,<0.4.0
    - astroid >=2.12.10,<3.0.0
    - black >=22.8.0,<23.0.0
    - bytecode >=0,<1
    - jellyfish >=0,<1
    - jinja2 >=3.1,<4.0
    - mutpy-pynguin >=0.7.1,<0.8.0
    - networkx >=2.8.6,<3.0.0
    - pydot >=1.4,<2.0
    - pygments >=2.13,<3.0
    - pytest >=7.1,<8.0
    - python >=3.10,<3.11
    - rich >=12.5,<13.0
    - simple-parsing >=0.0.20,<0.0.21
    - typing_inspect >=0,<1

test:
  commands:
    - pip check
    - export PYNGUIN_DANGER_AWARE=1
    - python -c 'import pynguin'
    - pynguin
  requires:
    - pip

about:
  home: https://github.com/se2p/pynguin
  doc_url: https://pynguin.readthedocs.io/en/latest/
  summary: Pynguin is a tool for automated unit test generation for Python
  license: LGPL-3.0-only
  license_file: LICENSE.rst
  description: |
    Unit test automated generation techniques have been proposed and mature
     tools exist for statically typed languages, such as Java. Pynguin is on of
     the first tool that fills this gap and allows the automated generation of
     unit tests for Python programs.

extra:
  recipe-maintainers:
    - thewchan
