schema_version: 1

context:
  python_min: 3.10
  name: pynguin
  version: 0.41.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pynguin-${{ version }}.tar.gz
  sha256: dd1222f9631d79fbe6c9360a92cdec60aa479501adc8a112c776e980142e2e4b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - pynguin = pynguin.cli:main

requirements:
  host:
    - pip
    - poetry-core
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }},<3.11
    - astroid >=3.3.9,<4.0.0
    - black >=25.1.0,<26.0.0
    - bytecode >=0.16.1,<0.17.0
    - dill >=0.3.9,<0.4.0
    - jinja2 >=3.1.6,<4.0.0
    - networkx >=3.4.0,<4.0.0
    - multiprocess >=0.70.16,<0.71.0
    - rich >=14.0.0,<15.0.0
    - pygments >=2.19.1,<3.0.0
    - pytest >=8.3.5,<9.0.0
    - simple-parsing >=0.1.7,<0.2.0
    - typing_inspect >=0.9.0,<0.10.0
    - asciitree >=0.3.3,<0.4.0
    - libcst >=1.7.0,<2.0.0
    - setuptools >=78.1,<79.0
    - toml >=0.10.2,<0.11.0
    - psutil >=7.0.0,<8.0.0
    # Not listed but needed for import test
    - numpy

tests:
  # Import test in script, no pip check because doesn't work with bytecode
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - export PYNGUIN_DANGER_AWARE=1
      - "python -c 'import pynguin'"
      - pynguin

about:
  summary: Pynguin is a tool for automated unit test generation for Python
  license: LGPL-3.0-only
  license_file: LICENSE.rst
  description: |
    Unit test automated generation techniques have been proposed and mature
    tools exist for statically typed languages, such as Java. Pynguin is on of
    the first tool that fills this gap and allows the automated generation of
    unit tests for Python programs.


  homepage: https://github.com/se2p/pynguin
  documentation: https://pynguin.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - thewchan
